name: Monitoring Deployment Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
    paths:
      - terraform/monitoring/**

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  react-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: terraform/monitoring

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/monitoring

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: terraform/monitoring

      - name: Terraform Apply
        if: github.event.pull_request.merged == true
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: terraform/monitoring

