name: React CI Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
    paths:
      - codebase/rdicidr-0.1.0/**
      - terraform/app/**

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  react-ci:
    runs-on: ubuntu-latest

    outputs:
      APPLY_STATUS_FLAG: ${{ steps.set_apply_flag.outputs.apply_status }}

    defaults:
      run:
        working-directory: codebase/rdicidr-0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 15
          cache: npm
          cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier -- --write

      - name: Test
        run: CI=true npm run test

      - name: Build
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: codebase/rdicidr-0.1.0/build
      
      - name: Set Apply Status Flag
        id: set_apply_flag
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "apply_status=true" >> $GITHUB_OUTPUT
          else
            echo "apply_status=false" >> $GITHUB_OUTPUT
          fi
      
  deploy:
    needs: react-ci
    uses: ./.github/workflows/react-cd.yml
    secrets: inherit
    with:
      apply_status: ${{ fromJSON(needs.react-ci.outputs.APPLY_STATUS_FLAG) }}